# Generated by Django 3.2.7 on 2021-10-07 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangement_advertiser', '0004_auto_20211006_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='advertiser_id',
            new_name='advertiser',
        ),
    ]
