# Generated by Django 3.2.7 on 2021-10-07 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangement_advertiser', '0005_rename_advertiser_id_ad_advertiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='advertiser',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mangement_advertiser.advertiser'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
