# Generated by Django 3.2.7 on 2021-10-07 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangement_advertiser', '0007_alter_advertiser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangement_advertiser.advertiser'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
