# Generated by Django 3.2.7 on 2021-10-09 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangement_advertiser', '0008_auto_20211007_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractClickViews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='ad',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='views',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='views',
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('abstractclickviews_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mangement_advertiser.abstractclickviews')),
            ],
            bases=('mangement_advertiser.abstractclickviews',),
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('abstractclickviews_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mangement_advertiser.abstractclickviews')),
            ],
            bases=('mangement_advertiser.abstractclickviews',),
        ),
        migrations.AddField(
            model_name='abstractclickviews',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangement_advertiser.ad'),
        ),
        migrations.AddField(
            model_name='abstractclickviews',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangement_advertiser.advertiser'),
        ),
    ]
