# Generated by Django 3.2.7 on 2021-10-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangement_advertiser', '0011_ad_approve'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Views',
            new_name='View',
        ),
    ]
