# Generated by Django 3.2.7 on 2021-10-10 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangement_advertiser', '0014_alter_ad_advertiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='mangement_advertiser.advertiser'),
        ),
    ]
