# Generated by Django 3.2.7 on 2021-10-12 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangement_advertiser', '0017_dailyreport_hourlyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyTime', models.DateTimeField(auto_now_add=True)),
                ('count', models.BigIntegerField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangement_advertiser.ad')),
            ],
        ),
        migrations.DeleteModel(
            name='DailyReport',
        ),
        migrations.DeleteModel(
            name='HourlyReport',
        ),
        migrations.CreateModel(
            name='DailyClickReport',
            fields=[
                ('abstractreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mangement_advertiser.abstractreport')),
            ],
            bases=('mangement_advertiser.abstractreport',),
        ),
        migrations.CreateModel(
            name='DailyViewReport',
            fields=[
                ('abstractreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mangement_advertiser.abstractreport')),
            ],
            bases=('mangement_advertiser.abstractreport',),
        ),
        migrations.CreateModel(
            name='HourlyClickReport',
            fields=[
                ('abstractreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mangement_advertiser.abstractreport')),
            ],
            bases=('mangement_advertiser.abstractreport',),
        ),
        migrations.CreateModel(
            name='HourlyViewReport',
            fields=[
                ('abstractreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mangement_advertiser.abstractreport')),
            ],
            bases=('mangement_advertiser.abstractreport',),
        ),
    ]
